
package proxy.bank;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertEuroToDirham", targetNamespace = "http://ws/", className = "proxy.bank.ConvertEuroToDirham")
    @ResponseWrapper(localName = "convertEuroToDirhamResponse", targetNamespace = "http://ws/", className = "proxy.bank.ConvertEuroToDirhamResponse")
    @Action(input = "http://ws/BankService/convertEuroToDirhamRequest", output = "http://ws/BankService/convertEuroToDirhamResponse")
    public double convertEuroToDirham(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertDirhamToEuro", targetNamespace = "http://ws/", className = "proxy.bank.ConvertDirhamToEuro")
    @ResponseWrapper(localName = "convertDirhamToEuroResponse", targetNamespace = "http://ws/", className = "proxy.bank.ConvertDirhamToEuroResponse")
    @Action(input = "http://ws/BankService/convertDirhamToEuroRequest", output = "http://ws/BankService/convertDirhamToEuroResponse")
    public double convertDirhamToEuro(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.bank.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://ws/", className = "proxy.bank.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://ws/", className = "proxy.bank.GetAccountsResponse")
    @Action(input = "http://ws/BankService/getAccountsRequest", output = "http://ws/BankService/getAccountsResponse")
    public List<Account> getAccounts();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.bank.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "proxy.bank.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "proxy.bank.GetAccountResponse")
    @Action(input = "http://ws/BankService/getAccountRequest", output = "http://ws/BankService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
